#!/bin/sh

#Install dev packages
yum -y -q install gcc python27 libevent-devel.x86_64 python27-devel.x86_64

if ! hash pip 2>/dev/null; then
	#Install pip
	wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py
	wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py
	python27 ez_setup.py
	python27 get-pip.py
	rm ez_setup.py
	rm get-pip.py
fi

#Install greenlet
installed=`pip list | grep greenlet`
if [ ! "$installed" ]; then
	pip install greenlet
fi

#Install gevent
installed=`pip list | grep gevent`
if [ ! "$installed" ]; then
	pip install gevent
fi
